baseURL = 'https://www.therpggame.com/'
languageCode = 'it-it'
title = 'ILGDR! Devblog'
theme = 'PaperMod'

[params]
    # Indichiamo a PaperMod dove sono i post per la Home Page
    mainSections = ["posts"]
    
    # Opzioni specifiche per PaperMod
    defaultTheme = "auto"
    showCodeCopyButtons = true
    showReadingTime = true