baseURL = 'https://www.therpggame.com/'
languageCode = 'it-it'
title = 'ILGDR! Devblog'
theme = 'PaperMod'

[params]
    # Descrizione per il Meta
    description = "Il devblog ufficiale di ILGDR! - Un viaggio nello sviluppo di un GDR testuale unico."

    # Indichiamo a PaperMod dove sono i post per la Home Page
    mainSections = ["posts"]
    
    # Opzioni specifiche per PaperMod
    defaultTheme = "auto"
    showCodeCopyButtons = true
    showReadingTime = true

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/NinNonNan"

    [[params.socialIcons]]
    name = "kofi"
    url = "https://ko-fi.com/therpggame"